name: "bde_at3_airbnb"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  bde_at3_airbnb:
    # Config for Bronze Layer
    bronze:
      +materialized: view      # <--- CHANGED: Use view to avoid data duplication
      +schema: bronze          # Creates schema 'target_schema_bronze'
      +tags: ["bronze"]

    # Config for Silver Layer
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver"]

    # Config for Gold Layer
    gold:
      star:
        +materialized: table
        +schema: gold
        +tags: ["gold", "star_schema"]
      mart:
        +materialized: view
        +schema: gold
        +tags: ["gold", "datamart"]

snapshots:
  bde_at3_airbnb:
    +target_schema: silver      # Snapshots usually live in Silver (or a dedicated schema)