name: "airbnb_census_warehouse"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  airbnb_census_warehouse:
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ["bronze"]

    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver"]

    gold:
      star:
        +materialized: table
        +schema: gold
        +tags: ["gold", "star_schema"]
      mart:
        +materialized: view
        +schema: gold
        +tags: ["gold", "datamart"]

snapshots:
  airbnb_census_warehouse:
    +target_schema: silver
